api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.PersonView.as_view(),name='Person'),
    path('add/', views.WeatherView.as_view(), name='Weather'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.emp)
]

viva/urls.py
from django.contrib import admin
from django.urls import path,include

# these lines are import for Media
from django.conf import settings
from django.conf.urls.static import static
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('blog/',include('blog.urls')),
    path('mail/',include('mail.urls')),
    path('sms/',include('sms.urls')),
    path('shop/',include('shop.urls')),
    path('signup/',include('signup.urls')),
    path('contact/',include('contact.urls')),
    path('payment/',include('payment.urls')),
    path('api/',include('api.urls')),
    path('emp', views.emp),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Employee(models.Model):
    eid = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    experience = models.IntegerField()
    designation = models.CharField(max_length=30)
    email = models.EmailField()
    contact = models.CharField(max_length=15)
    address = models.CharField(max_length=100)

    class Meta:
        db_table = "employee"
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

blog/views.py
from django.shortcuts import render, redirect
from blog.forms import EmployeeForm
from blog.models import Employee
from viva import settings

def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request,'blog/index.html',{"BASE_URL":settings.Base_url,'form':form})

def show(request):
    employee = Employee.objects.all()
    return render(request,"blog/show.html",{"BASE_URL":settings.Base_url,'employee': employee})

def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request,'blog/edit.html',{"BASE_URL":settings.Base_url,'employee': employee})

def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'blog/edit.html',{"BASE_URL":settings.Base_url,'employee': employee})

def delete(request, id):
        employee = Employee.objects.get(id=id)
        employee.delete()
        return redirect("/show")

templates/blog/edit.html
{% extends 'base-templates.html' %}
{% block content %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}"/>

<form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Experience:</label>
    <div class="col-sm-4">
        <input type="text" name="experience" id="id_experience" required maxlength="254" value="{{ employee.experience }}" />
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Designation:</label>
    <div class="col-sm-4">
        <input type="text" name="designation" id="id_designation" required maxlength="15" value="{{ employee.designation }}" />
    </div>
  </div>

   <div class="form-group row">
    <label class="col-sm-2 col-form-label">Email:</label>
    <div class="col-sm-4">
        <input type="email" name="email" id="id_email" required maxlength="15" value="{{ employee.email }}" />
    </div>
  </div>

   <div class="form-group row">
    <label class="col-sm-2 col-form-label">Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="contact" id="id_contact" required maxlength="15" value="{{ employee.contact }}" />
    </div>
  </div>

   <div class="form-group row">
    <label class="col-sm-2 col-form-label">Address:</label>
    <div class="col-sm-4">
        <input type="text" name="address" id="id_address" required maxlength="15" value="{{ employee.address }}" />
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>

{% endblock %}

templates/blog/index.html
{% extends 'base-templates.html' %}
{% block content %}
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/style.css' %}"/>

<form method="POST" class="post-form" action="/emp">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
      {{ form.eid }}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
      {{ form.name }}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Experience:</label>
    <div class="col-sm-4">
      {{ form.experience }}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Designation:</label>
    <div class="col-sm-4">
      {{ form.designation }}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Email:</label>
    <div class="col-sm-4">
      {{ form.email }}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Contact:</label>
    <div class="col-sm-4">
      {{ form.contact }}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Address:</label>
    <div class="col-sm-4">
      {{ form.address }}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>

{% endblock %}

templates/blog/show.html
{% extends 'base-templates.html' %}
{% block content %}

<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Experience</th>
        <th>Designation </th>
        <th>Email </th>
        <th>Contact </th>
        <th>Address </th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for employee in employee %}
<!-- 'employee' variable and 'employees' views.py file key  -->
    <tr>
        <td>{{ employee.eid }}</td>
        <td>{{ employee.ename }}</td>
        <td>{{ employee.experience }}</td>
        <td>{{ employee.designation }}</td>
        <td>{{ employee.email }}</td>
        <td>{{ employee.contact }}</td>
        <td>{{ employee.address }}</td>
        <td>
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ employee.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>

{% endblock %}